// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ5Y9x6hJJq1Nk04jy6rE5R1mghxoSUjM',
    appId: '1:723356367770:web:268e45f3316b7579a51823',
    messagingSenderId: '723356367770',
    projectId: 'cognitive-load-ai',
    authDomain: 'cognitive-load-ai.firebaseapp.com',
    storageBucket: 'cognitive-load-ai.firebasestorage.app',
    measurementId: 'G-D63Q6F959V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdznnUVA9TwPPaXbp5C-c3I1suVKWavow',
    appId: '1:723356367770:android:04d4b72d34be360aa51823',
    messagingSenderId: '723356367770',
    projectId: 'cognitive-load-ai',
    storageBucket: 'cognitive-load-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASkqBgXWk-ithfpVcJyY6X35NI7_qDBbI',
    appId: '1:723356367770:ios:b149d68a91bb9bdea51823',
    messagingSenderId: '723356367770',
    projectId: 'cognitive-load-ai',
    storageBucket: 'cognitive-load-ai.firebasestorage.app',
    iosBundleId: 'com.example.cognitiveloadAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASkqBgXWk-ithfpVcJyY6X35NI7_qDBbI',
    appId: '1:723356367770:ios:b149d68a91bb9bdea51823',
    messagingSenderId: '723356367770',
    projectId: 'cognitive-load-ai',
    storageBucket: 'cognitive-load-ai.firebasestorage.app',
    iosBundleId: 'com.example.cognitiveloadAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ5Y9x6hJJq1Nk04jy6rE5R1mghxoSUjM',
    appId: '1:723356367770:web:2b5767f0757b9292a51823',
    messagingSenderId: '723356367770',
    projectId: 'cognitive-load-ai',
    authDomain: 'cognitive-load-ai.firebaseapp.com',
    storageBucket: 'cognitive-load-ai.firebasestorage.app',
    measurementId: 'G-CF6STB7KQE',
  );
}
